# Generated by Django 2.1.7 on 2019-03-20 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.GithubUser')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('manifest_path', models.CharField(max_length=255)),
                ('requirements', models.CharField(max_length=64)),
                ('dismissed', models.BooleanField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=8)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('vulnerableVersions', models.CharField(max_length=64)),
                ('package', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='organisationuser',
            index=models.Index(fields=['user', 'org'], name='organisation_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationuser',
            unique_together={('user', 'org')},
        ),
    ]
