# Generated by Django 2.1.7 on 2019-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubuser',
            name='user',
        ),
        migrations.AddField(
            model_name='githubuser',
            name='oauth_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubuser',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
