# Generated by Django 2.1.7 on 2019-03-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0004_vulnerability_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='orgs_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='repos_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='vuln_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
