# Generated by Django 2.1.7 on 2019-03-25 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0005_auto_20190325_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackInstance',
            fields=[
                ('team_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('oauth_token', models.CharField(max_length=255)),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
