# Generated by Django 2.1.7 on 2019-03-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0006_slackinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackRepoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=255)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.Repository')),
                ('slack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.SlackInstance')),
            ],
        ),
        migrations.CreateModel(
            name='SlackVulnerabilitySent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.SlackRepoLink')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.Vulnerability')),
            ],
        ),
        migrations.AddIndex(
            model_name='slackvulnerabilitysent',
            index=models.Index(fields=['slack', 'vulnerability'], name='slack_vulnerability_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slackvulnerabilitysent',
            unique_together={('slack', 'vulnerability')},
        ),
        migrations.AddIndex(
            model_name='slackrepolink',
            index=models.Index(fields=['slack', 'repo'], name='slack_repo_link_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slackrepolink',
            unique_together={('slack', 'repo')},
        ),
    ]
