# Generated by Django 2.1.7 on 2019-04-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0007_auto_20190325_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='user_organisation',
            field=models.BooleanField(default=False),
        ),
    ]
