# Generated by Django 2.2 on 2019-04-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0008_organisation_user_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackinstance',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
