# Generated by Django 2.2 on 2019-04-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0009_slackinstance_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackOrgLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='slackvulnerabilitysent',
            name='slack_vulnerability_idx',
        ),
        migrations.AddField(
            model_name='slackvulnerabilitysent',
            name='slack_repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifier.SlackRepoLink'),
        ),
        migrations.AlterUniqueTogether(
            name='slackvulnerabilitysent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='slackorglink',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.Organisation'),
        ),
        migrations.AddField(
            model_name='slackorglink',
            name='slack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.SlackInstance'),
        ),
        migrations.RemoveField(
            model_name='slackvulnerabilitysent',
            name='slack',
        ),
        migrations.AddField(
            model_name='slackvulnerabilitysent',
            name='slack_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifier.SlackOrgLink'),
        ),
        migrations.AddIndex(
            model_name='slackorglink',
            index=models.Index(fields=['slack', 'org'], name='slack_org_link_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slackorglink',
            unique_together={('slack', 'org')},
        ),
        migrations.AddIndex(
            model_name='slackvulnerabilitysent',
            index=models.Index(fields=['slack_org', 'vulnerability'], name='slack_vulnerability_org_idx'),
        ),
        migrations.AddIndex(
            model_name='slackvulnerabilitysent',
            index=models.Index(fields=['slack_repo', 'vulnerability'], name='slack_vulnerability_repo_idx'),
        ),
    ]
