# Generated by Django 2.2 on 2019-05-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0011_vulnerability_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='webhook_id',
            field=models.IntegerField(null=True),
        ),
    ]
