# Generated by Django 2.2 on 2019-05-07 20:56

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0012_repository_webhook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='webhook_secret',
            field=models.CharField(default=secrets.token_urlsafe, max_length=32),
        ),
    ]
