# Generated by Django 2.2 on 2019-05-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0013_githubuser_webhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='oauth_token',
            field=models.TextField(),
        ),
    ]
