# Generated by Django 2.2 on 2019-05-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0014_auto_20190510_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackinstance',
            name='oauth_token',
            field=models.TextField(),
        ),
    ]
