# Generated by Django 2.2 on 2019-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0015_auto_20190510_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='webhook_id',
            field=models.IntegerField(null=True),
        ),
    ]
